# Generated by Django 5.2.8 on 2026-01-18 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='description',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='temperature',
        ),
        migrations.AlterField(
            model_name='notification',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='cities.city'),
        ),
    ]
