runtime: python312

entrypoint: gunicorn --chdir src config.wsgi:application --bind :$PORT

handlers:
  - url: /static
    static_dir: staticfiles

  - url: /.*
    script: auto


env_variables:
  DB_PASSWORD: "django-weather-reminder:europe-west1:weather-db"
  INSTANCE_CONNECTION_NAME: "django-weather-reminder:europe-west1:weather-db"